### ISSUE TITLE
GPU plan?

### ISSUE THREAD

**Issue by Moelf** [JuliaHEP/JetReconstruction.jl#52]
Is there way to somehow make the algorithms GPU-able?

**Comment by graeme-a-stewart** [comment]
I'd say it is pretty hard - the algorithms are very sequential by nature, which is not enjoyed by GPUs. The most promising approach might be to parallelise across events, rather than try to parallelise within an event.

Alternatively, one could investigate more parallelisable clustering approaches, like cellular automata or maybe even an ML inference algorithm for clustering.

Stretch goal, but interesting...

**Comment by Moelf** [comment]
I was thinking parallel over events!

**Comment by graeme-a-stewart** [comment]
Sort of... but one would need to see if the code for the CPU version is going to go onto a GPU to do each of the events. The data structures for the plain algorithm would be a lot easier and would probably accelerate well. For the tiled algorithm my gut feeling is it would be a lot of work, as the whole thrust there is to use more complex logic to reduce the computational burden. e.g., linked lists and the whole tiling setup, so the data layouts are not at all GPU friendly.

So the plain algorithm would be the one to target IMO.

**Comment by graeme-a-stewart** [comment]
Although I should say from the outset that at the typical particle densities where N2Plain is used (Z->ee) the typical jet reconstruction time is O(10μs), so this is not, per-se, a real target for GPU running.

**Comment by graeme-a-stewart** [comment]
I think we discussed this enough and it's not an open issue right now - thanks for prompting it @Moelf!
